# Generated by Django 4.1.7 on 2023-03-15 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderQuantitys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.package')),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='orderQuantity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.orderquantitys'),
        ),
        migrations.DeleteModel(
            name='OrderQuantity',
        ),
    ]
