# Generated by Django 4.1.7 on 2023-03-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_orderquantitys_alter_certificate_orderquantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderQuantitys',
            new_name='OrderQuantity',
        ),
    ]
