# Generated by Django 4.1.7 on 2023-03-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_orderquantitys_orderquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='receiverEmail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='receiverName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
