# Generated by Django 4.1.7 on 2023-03-15 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_certificate_receiveremail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartQuantitys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.cart')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.package')),
            ],
        ),
        migrations.DeleteModel(
            name='CartQuantity',
        ),
    ]
